@echo off
devmanview.exe /enable "PCI Data Acquisition and Signal Processing Controller"
devmanview.exe /enable "PCI Encryption/Decryption Controller"
devmanview.exe /enable "PCI Simple Communications Controller"
devmanview.exe /enable "PCI Memory Controller"
devmanview.exe /enable "PCI standard RAM Controller"
devmanview.exe /enable "AMD PSP"
devmanview.exe /enable "AMD SMBus"
devmanview.exe /enable "AURA LED Controller"
devmanview.exe /enable "Fax"
devmanview.exe /enable "Microsoft Print to PDF"
devmanview.exe /enable "Microsoft XPS Document Writer"
devmanview.exe /enable "Root Print Queue"
devmanview.exe /enable "Base System Device"
devmanview.exe /enable "Composite Bus Enumerator"
devmanview.exe /enable "UMBus Root Bus Enumerator"
devmanview.exe /enable "Direct memory access controller"
devmanview.exe /enable "Generic Bluetooth Adapter"
devmanview.exe /enable "Intel SMBus"
devmanview.exe /enable "Intel(R) Display Audio"
devmanview.exe /enable "Intel(R) Management Engine Interface"
devmanview.exe /enable "Programmable Interrupt Controller"
devmanview.exe /enable "Legacy device"
devmanview.exe /enable "Microsoft Device Association Root Enumerator"
devmanview.exe /enable "Microsoft GS Wavetable Synth"
devmanview.exe /enable "Microsoft Hyper-V Virtualization Infrastructure Driver"
devmanview.exe /enable "Microsoft Input Configuration Device"
devmanview.exe /enable "Microsoft Kernel Debug Network Adapter"
devmanview.exe /enable "Microsoft Radio Device Enumeration Bus"
devmanview.exe /enable "Microsoft RRAS Root Enumerator"
devmanview.exe /enable "Microsoft Virtual Drive Enumerator"
devmanview.exe /enable "Microsoft RRAS Root Enumerator"
devmanview.exe /enable "Remote Desktop Device Redirector Bus"
devmanview.exe /enable "Numeric Data Processor"
devmanview.exe /enable "System Speaker"
