@echo off
devmanview.exe /disable "Motherboard Resources"
devmanview.exe /disable "PCI Data Acquisition and Signal Processing Controller"
devmanview.exe /disable "PCI Encryption/Decryption Controller"
devmanview.exe /disable "PCI Simple Communications Controller"
devmanview.exe /disable "PCI Memory Controller"
devmanview.exe /disable "PCI standard RAM Controller"
devmanview.exe /disable "AMD PSP"
devmanview.exe /disable "AMD SMBus"
devmanview.exe /disable "AURA LED Controller"
devmanview.exe /disable "Fax"
devmanview.exe /disable "Microsoft Print to PDF"
devmanview.exe /disable "Microsoft XPS Document Writer"
devmanview.exe /disable "Root Print Queue"
devmanview.exe /disable "Base System Device"
devmanview.exe /disable "Composite Bus Enumerator"
devmanview.exe /disable "UMBus Root Bus Enumerator"
devmanview.exe /disable "Direct memory access controller"
devmanview.exe /disable "Generic Bluetooth Adapter"
devmanview.exe /disable "Intel SMBus"
devmanview.exe /disable "Intel(R) Display Audio"
devmanview.exe /disable "Intel(R) Management Engine Interface"
devmanview.exe /disable "Programmable Interrupt Controller"
devmanview.exe /disable "Legacy device"
devmanview.exe /disable "Microsoft Device Association Root Enumerator"
devmanview.exe /disable "Microsoft GS Wavetable Synth"
devmanview.exe /disable "Microsoft Hyper-V Virtualization Infrastructure Driver"
devmanview.exe /disable "Microsoft Input Configuration Device"
devmanview.exe /disable "Microsoft Kernel Debug Network Adapter"
devmanview.exe /disable "Microsoft Radio Device Enumeration Bus"
devmanview.exe /disable "Microsoft RRAS Root Enumerator"
devmanview.exe /disable "Microsoft Virtual Drive Enumerator"
devmanview.exe /disable "Microsoft RRAS Root Enumerator"
devmanview.exe /disable "Remote Desktop Device Redirector Bus"
devmanview.exe /disable "Numeric Data Processor"
devmanview.exe /disable "System Speaker"
devmanview.exe /uninstall "File as Volume Driver"
